### ISSUE TITLE
When lang parameter is set and lang file missing then use default file

### ISSUE THREAD

**Issue by stephane-klein** [spacefill/gibbon-mail#3]
@eliasdemnati I suggest to improve the multi-language support:

If this request is send:

```
{
  "from": "no-reply@example.com",
  "to": "john.doe@example.com",
  "lang": "de"
}
```

and one `de.[text|subject|mjml]` files missing then Gibbon mail must use `default.[text|subject|mjml]` file.

I think the code must be updated [here](https://github.com/spacefill/gibbon-mail/blob/bda17b01a74f7abbdab8aa3476b38a7c3c63ab3d/backend/src/app.js#L146).

If this suggestion is implemented, then don't forget to update the documentation.

**Comment by eliasdemnati** [comment]
@stephane-klein This is already implemented here: https://github.com/spacefill/gibbon-mail/blob/bda17b01a74f7abbdab8aa3476b38a7c3c63ab3d/backend/src/app.js#L187

I feel like the documentation is pretty clear also: https://github.com/spacefill/gibbon-mail#how-does-the-multi-language-support-works

`You also need to let a default file in case the language is not found or no language is requested.`

So I'm not really sure what is the problem ?

**Comment by MichaelTSS** [comment]
@stephane-klein @eliasdemnati 

I think it would be nice if the [README.md](https://github.com/spacefill/gibbon-mail#how-does-the-multi-language-support-works) could include some examples :

- how to add one language and set all others to default to the one language
- how to add two languages and set all others to default to one of the two languages

**Comment by stephane-klein** [comment]
@eliasdemnati ok, this feature is already implemented.

I suggest to improve readme with a explicit example.
